"""Seed 20 task templates into the database."""

import asyncio
from decimal import Decimal

from sqlalchemy import select

from app.database import async_session_factory, engine, Base
from app.models.task import TaskTemplate


TASK_TEMPLATES = [
    # Kitchen (5)
    {
        "title": "Wash a Dish",
        "title_zh": "洗碗",
        "category": "kitchen",
        "difficulty": "easy",
        "description": "Record yourself washing a single dish under running water, including soaping, scrubbing, and rinsing.",
        "steps": [
            "Place dish under faucet",
            "Apply dish soap with sponge",
            "Scrub all surfaces",
            "Rinse under running water",
            "Place dish on drying rack",
        ],
        "payout_usd": Decimal("0.50"),
        "duration_min": 30,
        "duration_max": 90,
        "hands_required": "two",
        "objects_expected": ["dish", "sponge", "soap", "faucet"],
        "camera_position": "overhead or side angle, 30-60cm distance",
    },
    {
        "title": "Cut a Fruit",
        "title_zh": "切水果",
        "category": "kitchen",
        "difficulty": "medium",
        "description": "Record yourself cutting a piece of fruit (apple, orange, or banana) with a knife on a cutting board.",
        "steps": [
            "Place fruit on cutting board",
            "Pick up knife",
            "Cut fruit in half",
            "Slice into smaller pieces",
            "Set knife down safely",
        ],
        "payout_usd": Decimal("0.75"),
        "duration_min": 20,
        "duration_max": 60,
        "hands_required": "two",
        "objects_expected": ["fruit", "knife", "cutting board"],
        "camera_position": "overhead, 40-60cm distance",
    },
    {
        "title": "Pour Water into a Glass",
        "title_zh": "倒水",
        "category": "kitchen",
        "difficulty": "easy",
        "description": "Record yourself pouring water from a bottle or pitcher into a glass without spilling.",
        "steps": [
            "Pick up water container",
            "Position glass on stable surface",
            "Tilt container to pour",
            "Fill glass to desired level",
            "Set container back down",
        ],
        "payout_usd": Decimal("0.40"),
        "duration_min": 10,
        "duration_max": 30,
        "hands_required": "two",
        "objects_expected": ["bottle", "glass"],
        "camera_position": "side angle, 30-50cm distance",
    },
    {
        "title": "Use Chopsticks",
        "title_zh": "使用筷子",
        "category": "kitchen",
        "difficulty": "medium",
        "description": "Record yourself picking up small food items (noodles, peanuts, or diced tofu) with chopsticks.",
        "steps": [
            "Hold chopsticks correctly",
            "Position chopsticks over food",
            "Grip a single piece",
            "Lift and transfer to mouth or plate",
            "Repeat 3-5 times",
        ],
        "payout_usd": Decimal("0.60"),
        "duration_min": 20,
        "duration_max": 60,
        "hands_required": "one",
        "objects_expected": ["chopsticks", "bowl", "food items"],
        "camera_position": "front-facing, 30-50cm distance",
    },
    {
        "title": "Wipe a Table",
        "title_zh": "擦桌子",
        "category": "kitchen",
        "difficulty": "easy",
        "description": "Record yourself wiping down a table surface with a cloth or sponge until clean.",
        "steps": [
            "Pick up cleaning cloth",
            "Spray cleaner or dampen cloth",
            "Wipe table in broad strokes",
            "Focus on any spots or stains",
            "Wring out and set cloth aside",
        ],
        "payout_usd": Decimal("0.40"),
        "duration_min": 15,
        "duration_max": 45,
        "hands_required": "one",
        "objects_expected": ["cloth", "table", "spray bottle"],
        "camera_position": "overhead or elevated side, 50-80cm distance",
    },
    # Cleaning (4)
    {
        "title": "Fold a T-Shirt",
        "title_zh": "叠T恤",
        "category": "cleaning",
        "difficulty": "easy",
        "description": "Record yourself folding a t-shirt neatly using any folding method.",
        "steps": [
            "Lay t-shirt flat, front down",
            "Fold one side toward center",
            "Fold sleeve back",
            "Repeat on other side",
            "Fold bottom up to collar",
        ],
        "payout_usd": Decimal("0.40"),
        "duration_min": 15,
        "duration_max": 45,
        "hands_required": "two",
        "objects_expected": ["t-shirt", "flat surface"],
        "camera_position": "overhead, 50-70cm distance",
    },
    {
        "title": "Fold a Towel",
        "title_zh": "叠毛巾",
        "category": "cleaning",
        "difficulty": "easy",
        "description": "Record yourself folding a bath towel into a neat rectangle.",
        "steps": [
            "Spread towel flat",
            "Fold in half lengthwise",
            "Fold in half again",
            "Fold into thirds",
            "Smooth edges and stack",
        ],
        "payout_usd": Decimal("0.40"),
        "duration_min": 15,
        "duration_max": 45,
        "hands_required": "two",
        "objects_expected": ["towel", "flat surface"],
        "camera_position": "overhead, 60-80cm distance",
    },
    {
        "title": "Clean a Window",
        "title_zh": "擦窗户",
        "category": "cleaning",
        "difficulty": "medium",
        "description": "Record yourself cleaning a window or glass surface with spray and cloth until streak-free.",
        "steps": [
            "Spray glass cleaner on surface",
            "Wipe with cloth in circular motions",
            "Switch to straight vertical strokes",
            "Buff dry with clean cloth",
            "Inspect for streaks",
        ],
        "payout_usd": Decimal("0.60"),
        "duration_min": 30,
        "duration_max": 90,
        "hands_required": "two",
        "objects_expected": ["spray bottle", "cloth", "window"],
        "camera_position": "side angle, 40-80cm distance",
    },
    {
        "title": "Make a Bed",
        "title_zh": "整理床铺",
        "category": "cleaning",
        "difficulty": "hard",
        "description": "Record yourself making a bed from unmade state: straighten sheet, arrange blanket, fluff pillows.",
        "steps": [
            "Pull fitted sheet tight at corners",
            "Spread flat sheet evenly",
            "Layer blanket or comforter",
            "Tuck sides neatly",
            "Fluff and arrange pillows",
        ],
        "payout_usd": Decimal("1.00"),
        "duration_min": 60,
        "duration_max": 180,
        "hands_required": "two",
        "objects_expected": ["bed", "sheet", "blanket", "pillows"],
        "camera_position": "elevated side angle, 1-2m distance",
    },
    # Organization (3)
    {
        "title": "Organize a Drawer",
        "title_zh": "整理抽屉",
        "category": "organization",
        "difficulty": "medium",
        "description": "Record yourself organizing a messy drawer by sorting items into groups and arranging neatly.",
        "steps": [
            "Open drawer fully",
            "Remove all items",
            "Sort items into categories",
            "Place items back in organized groups",
            "Close drawer",
        ],
        "payout_usd": Decimal("0.75"),
        "duration_min": 60,
        "duration_max": 180,
        "hands_required": "two",
        "objects_expected": ["drawer", "miscellaneous items"],
        "camera_position": "overhead looking into drawer, 40-60cm distance",
    },
    {
        "title": "Arrange Books on a Shelf",
        "title_zh": "整理书架",
        "category": "organization",
        "difficulty": "easy",
        "description": "Record yourself arranging 5-10 books on a shelf by size or category.",
        "steps": [
            "Remove books from shelf",
            "Sort by height or category",
            "Place books upright on shelf",
            "Align spines evenly",
            "Adjust spacing",
        ],
        "payout_usd": Decimal("0.50"),
        "duration_min": 30,
        "duration_max": 90,
        "hands_required": "two",
        "objects_expected": ["books", "shelf"],
        "camera_position": "front-facing, 50-80cm distance",
    },
    {
        "title": "Sort Mixed Items",
        "title_zh": "分类物品",
        "category": "organization",
        "difficulty": "easy",
        "description": "Record yourself sorting a mixed pile of items (coins, buttons, or LEGO) by color, size, or type.",
        "steps": [
            "Spread items on flat surface",
            "Identify sorting categories",
            "Pick up items one by one",
            "Place into correct group",
            "Verify all items sorted",
        ],
        "payout_usd": Decimal("0.50"),
        "duration_min": 30,
        "duration_max": 90,
        "hands_required": "two",
        "objects_expected": ["mixed items", "containers or areas for sorting"],
        "camera_position": "overhead, 30-50cm distance",
    },
    # Assembly (3)
    {
        "title": "Screw in a Bolt",
        "title_zh": "拧螺丝",
        "category": "assembly",
        "difficulty": "medium",
        "description": "Record yourself screwing a bolt into a nut or threaded hole using fingers or a wrench.",
        "steps": [
            "Hold bolt and nut",
            "Align bolt with nut threads",
            "Turn clockwise by hand to start",
            "Tighten with wrench or pliers",
            "Verify it is secure",
        ],
        "payout_usd": Decimal("0.60"),
        "duration_min": 15,
        "duration_max": 45,
        "hands_required": "two",
        "objects_expected": ["bolt", "nut", "wrench"],
        "camera_position": "close-up side angle, 15-30cm distance",
    },
    {
        "title": "Plug in a USB Cable",
        "title_zh": "插USB线",
        "category": "assembly",
        "difficulty": "easy",
        "description": "Record yourself plugging a USB cable into a device port, including the orientation check.",
        "steps": [
            "Pick up USB cable",
            "Identify correct orientation",
            "Align with port",
            "Insert gently until click",
            "Verify connection (LED or screen)",
        ],
        "payout_usd": Decimal("0.35"),
        "duration_min": 10,
        "duration_max": 30,
        "hands_required": "two",
        "objects_expected": ["USB cable", "device with USB port"],
        "camera_position": "close-up, 10-20cm distance",
    },
    {
        "title": "Change a Light Bulb",
        "title_zh": "换灯泡",
        "category": "assembly",
        "difficulty": "medium",
        "description": "Record yourself removing an old light bulb and screwing in a new one (lamp must be off and cool).",
        "steps": [
            "Ensure lamp is OFF and cool",
            "Grip old bulb and turn counter-clockwise",
            "Remove old bulb",
            "Insert new bulb and turn clockwise",
            "Test by turning lamp on",
        ],
        "payout_usd": Decimal("0.60"),
        "duration_min": 15,
        "duration_max": 60,
        "hands_required": "two",
        "objects_expected": ["lamp or fixture", "light bulb"],
        "camera_position": "side angle, 30-50cm distance",
    },
    # Personal Care (3)
    {
        "title": "Tie Shoelaces",
        "title_zh": "系鞋带",
        "category": "personal_care",
        "difficulty": "easy",
        "description": "Record yourself tying shoelaces on a shoe using the bunny-ears or loop method.",
        "steps": [
            "Cross laces over each other",
            "Pull one under and tighten",
            "Make two loops (bunny ears)",
            "Cross loops and pull through",
            "Tighten the bow",
        ],
        "payout_usd": Decimal("0.40"),
        "duration_min": 10,
        "duration_max": 30,
        "hands_required": "two",
        "objects_expected": ["shoe with laces"],
        "camera_position": "overhead or front close-up, 20-40cm distance",
    },
    {
        "title": "Button a Shirt",
        "title_zh": "扣衬衫",
        "category": "personal_care",
        "difficulty": "medium",
        "description": "Record yourself buttoning up a dress shirt from bottom to top (at least 4 buttons).",
        "steps": [
            "Hold shirt open",
            "Start with bottom button",
            "Align button with buttonhole",
            "Push button through",
            "Repeat upward for each button",
        ],
        "payout_usd": Decimal("0.60"),
        "duration_min": 20,
        "duration_max": 60,
        "hands_required": "two",
        "objects_expected": ["button-up shirt"],
        "camera_position": "front-facing, 30-50cm distance",
    },
    {
        "title": "Zip a Jacket",
        "title_zh": "拉外套拉链",
        "category": "personal_care",
        "difficulty": "easy",
        "description": "Record yourself zipping up a jacket from bottom to top while wearing it.",
        "steps": [
            "Hold jacket sides together",
            "Insert pin into slider box",
            "Hold bottom with one hand",
            "Pull zipper up with other hand",
            "Zip to desired height",
        ],
        "payout_usd": Decimal("0.40"),
        "duration_min": 10,
        "duration_max": 30,
        "hands_required": "two",
        "objects_expected": ["jacket with zipper"],
        "camera_position": "front-facing, 30-60cm distance",
    },
    # Office (2)
    {
        "title": "Cut Paper with Scissors",
        "title_zh": "用剪刀剪纸",
        "category": "office",
        "difficulty": "easy",
        "description": "Record yourself cutting a piece of paper along a straight or curved line with scissors.",
        "steps": [
            "Place paper on flat surface",
            "Hold scissors in dominant hand",
            "Hold paper steady with other hand",
            "Cut along desired line",
            "Set scissors down safely",
        ],
        "payout_usd": Decimal("0.35"),
        "duration_min": 10,
        "duration_max": 30,
        "hands_required": "two",
        "objects_expected": ["paper", "scissors"],
        "camera_position": "overhead, 30-40cm distance",
    },
    {
        "title": "Staple Papers Together",
        "title_zh": "装订文件",
        "category": "office",
        "difficulty": "easy",
        "description": "Record yourself aligning 3-5 sheets of paper and stapling them in the corner.",
        "steps": [
            "Stack papers evenly",
            "Tap edges to align",
            "Position stapler at top-left corner",
            "Press stapler firmly",
            "Verify staple holds all sheets",
        ],
        "payout_usd": Decimal("0.35"),
        "duration_min": 10,
        "duration_max": 30,
        "hands_required": "two",
        "objects_expected": ["papers", "stapler"],
        "camera_position": "overhead or side, 20-40cm distance",
    },
]


async def seed():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session_factory() as session:
        # Check if tasks already exist
        result = await session.execute(select(TaskTemplate).limit(1))
        if result.scalar_one_or_none() is not None:
            print("Tasks already seeded. Skipping.")
            return

        for template_data in TASK_TEMPLATES:
            task = TaskTemplate(**template_data)
            session.add(task)

        await session.commit()
        print(f"Seeded {len(TASK_TEMPLATES)} task templates.")


if __name__ == "__main__":
    asyncio.run(seed())
