import type { Task, TaskCategory } from "./types";

export const MOCK_TASKS: Task[] = [
  // ── Kitchen (5) ──────────────────────────────────────────────
  {
    id: "wash_dish",
    title: "Wash a Dish",
    title_zh: "\u6d17\u7897",
    category: "kitchen",
    difficulty: "easy",
    description:
      "Record yourself washing a single dish under running water using a sponge. Ensure both hands, the dish, and the faucet are clearly visible throughout.",
    steps: [
      "Place a dirty dish in the sink",
      "Turn on the faucet to a steady stream",
      "Apply soap to the sponge",
      "Scrub the dish thoroughly on both sides",
      "Rinse the dish under running water",
      "Place the clean dish on a drying rack",
    ],
    payout_usd: 0.75,
    duration_min: 10,
    duration_max: 15,
    hands_required: "both",
    objects_expected: ["dish", "sponge", "faucet"],
    camera_position: "Front-facing, sink level",
    example_video_url: null,
    remaining_slots: 120,
    total_completed: 380,
  },
  {
    id: "cut_fruit",
    title: "Cut Fruit",
    title_zh: "\u5207\u6c34\u679c",
    category: "kitchen",
    difficulty: "medium",
    description:
      "Record yourself cutting a piece of fruit into slices or pieces on a cutting board. Both hands, the knife, and the fruit must be visible.",
    steps: [
      "Place the cutting board on a stable surface",
      "Position the fruit on the cutting board",
      "Hold the fruit steady with one hand",
      "Cut the fruit into even slices with a knife",
      "Arrange the slices on the board",
    ],
    payout_usd: 1.0,
    duration_min: 15,
    duration_max: 20,
    hands_required: "both",
    objects_expected: ["knife", "cutting board", "fruit"],
    camera_position: "Top-down or slight angle, table level",
    example_video_url: null,
    remaining_slots: 85,
    total_completed: 215,
  },
  {
    id: "pour_water",
    title: "Pour Water",
    title_zh: "\u5012\u6c34",
    category: "kitchen",
    difficulty: "easy",
    description:
      "Record yourself pouring water from a bottle into a cup. The pouring motion, bottle, and cup must all be clearly visible.",
    steps: [
      "Place a cup on a flat surface",
      "Pick up the water bottle",
      "Slowly pour water into the cup until 3/4 full",
      "Set the bottle down",
    ],
    payout_usd: 0.5,
    duration_min: 5,
    duration_max: 10,
    hands_required: "one",
    objects_expected: ["bottle", "cup"],
    camera_position: "Front-facing, table level",
    example_video_url: null,
    remaining_slots: 200,
    total_completed: 800,
  },
  {
    id: "use_chopsticks",
    title: "Use Chopsticks",
    title_zh: "\u7528\u7b77\u5b50\u5939\u83dc",
    category: "kitchen",
    difficulty: "medium",
    description:
      "Record yourself picking up food items from a bowl using chopsticks. Your hand grip and the food transfer must be clearly visible.",
    steps: [
      "Place a bowl of food on the table",
      "Hold the chopsticks with proper grip",
      "Pick up a piece of food from the bowl",
      "Transfer the food to another bowl or plate",
      "Repeat 2-3 times with different pieces",
    ],
    payout_usd: 1.0,
    duration_min: 10,
    duration_max: 15,
    hands_required: "one",
    objects_expected: ["chopsticks", "bowl", "food"],
    camera_position: "Slight angle from above, table level",
    example_video_url: null,
    remaining_slots: 95,
    total_completed: 305,
  },
  {
    id: "wipe_table",
    title: "Wipe Table",
    title_zh: "\u64e6\u684c\u5b50",
    category: "kitchen",
    difficulty: "easy",
    description:
      "Record yourself wiping down a table surface with a cloth. Show the wiping motion across the full surface area.",
    steps: [
      "Pick up the cleaning cloth",
      "Start wiping from one end of the table",
      "Use smooth, overlapping strokes",
      "Cover the entire table surface",
      "Fold the cloth and set it aside",
    ],
    payout_usd: 0.75,
    duration_min: 10,
    duration_max: 15,
    hands_required: "one",
    objects_expected: ["cloth", "table"],
    camera_position: "Side angle, showing full table surface",
    example_video_url: null,
    remaining_slots: 150,
    total_completed: 450,
  },

  // ── Cleaning (4) ─────────────────────────────────────────────
  {
    id: "fold_tshirt",
    title: "Fold T-Shirt",
    title_zh: "\u53e0T\u6064",
    category: "cleaning",
    difficulty: "easy",
    description:
      "Record yourself folding a t-shirt neatly using any folding method. The entire shirt and your hands must be visible throughout.",
    steps: [
      "Lay the t-shirt flat on a surface",
      "Smooth out any wrinkles",
      "Fold one side to the center",
      "Fold the other side to match",
      "Fold the bottom up to complete",
    ],
    payout_usd: 0.75,
    duration_min: 10,
    duration_max: 15,
    hands_required: "both",
    objects_expected: ["t-shirt"],
    camera_position: "Top-down, flat surface",
    example_video_url: null,
    remaining_slots: 180,
    total_completed: 620,
  },
  {
    id: "fold_towel",
    title: "Fold Towel",
    title_zh: "\u53e0\u6bdb\u5dfe",
    category: "cleaning",
    difficulty: "easy",
    description:
      "Record yourself folding a towel into a neat rectangle. Show the full towel and each fold clearly.",
    steps: [
      "Lay the towel flat on a surface",
      "Fold the towel in half lengthwise",
      "Fold in half again",
      "Make a final fold into a compact rectangle",
    ],
    payout_usd: 0.5,
    duration_min: 8,
    duration_max: 10,
    hands_required: "both",
    objects_expected: ["towel"],
    camera_position: "Top-down, flat surface",
    example_video_url: null,
    remaining_slots: 220,
    total_completed: 780,
  },
  {
    id: "clean_window",
    title: "Clean Window",
    title_zh: "\u64e6\u7a97\u6237",
    category: "cleaning",
    difficulty: "medium",
    description:
      "Record yourself cleaning a window or glass surface using spray and a cloth. Show the spraying and wiping motions clearly.",
    steps: [
      "Hold the spray bottle in one hand",
      "Spray the cleaning solution on the window",
      "Pick up the cleaning cloth",
      "Wipe the window in circular or zigzag motions",
      "Check for remaining streaks and re-wipe",
    ],
    payout_usd: 1.0,
    duration_min: 15,
    duration_max: 20,
    hands_required: "one",
    objects_expected: ["spray bottle", "cloth", "window"],
    camera_position: "Side angle, showing window surface",
    example_video_url: null,
    remaining_slots: 75,
    total_completed: 125,
  },
  {
    id: "make_bed",
    title: "Make Bed",
    title_zh: "\u6574\u7406\u5e8a\u94fa",
    category: "cleaning",
    difficulty: "medium",
    description:
      "Record yourself making a bed: straightening sheets, fluffing pillows, and arranging the blanket neatly.",
    steps: [
      "Pull the sheet flat across the mattress",
      "Tuck in the edges",
      "Fluff each pillow and place at the head",
      "Spread the blanket evenly",
      "Smooth out any wrinkles",
      "Adjust final positioning",
    ],
    payout_usd: 1.25,
    duration_min: 25,
    duration_max: 30,
    hands_required: "both",
    objects_expected: ["bed", "pillow", "blanket"],
    camera_position: "Wide angle from foot of bed",
    example_video_url: null,
    remaining_slots: 60,
    total_completed: 140,
  },

  // ── Organization (3) ─────────────────────────────────────────
  {
    id: "organize_drawer",
    title: "Organize Drawer",
    title_zh: "\u6574\u7406\u62bd\u5c49",
    category: "organization",
    difficulty: "medium",
    description:
      "Record yourself organizing items in a drawer. Show removing items, sorting them, and placing them back neatly.",
    steps: [
      "Open the drawer fully",
      "Remove all items from the drawer",
      "Sort items into categories",
      "Place items back in an organized arrangement",
      "Close the drawer to show the result",
    ],
    payout_usd: 1.25,
    duration_min: 25,
    duration_max: 30,
    hands_required: "both",
    objects_expected: ["drawer", "items"],
    camera_position: "Top-down or front-facing, drawer level",
    example_video_url: null,
    remaining_slots: 55,
    total_completed: 95,
  },
  {
    id: "arrange_books",
    title: "Arrange Books",
    title_zh: "\u6446\u653e\u4e66\u7c4d",
    category: "organization",
    difficulty: "easy",
    description:
      "Record yourself arranging a small stack of books onto a shelf. Show picking up each book and placing it upright.",
    steps: [
      "Pick up a book from the stack",
      "Place it upright on the shelf",
      "Repeat for each remaining book",
      "Straighten the row of books",
    ],
    payout_usd: 0.75,
    duration_min: 10,
    duration_max: 15,
    hands_required: "both",
    objects_expected: ["books", "shelf"],
    camera_position: "Front-facing, shelf level",
    example_video_url: null,
    remaining_slots: 130,
    total_completed: 270,
  },
  {
    id: "sort_items",
    title: "Sort Small Items",
    title_zh: "\u6536\u7eb3\u5c0f\u7269\u4ef6",
    category: "organization",
    difficulty: "easy",
    description:
      "Record yourself sorting small items (pens, clips, coins, etc.) into a container or organizer.",
    steps: [
      "Spread the items on a surface",
      "Identify categories for sorting",
      "Pick up items one by one",
      "Place each item in the appropriate section",
      "Show the organized result",
    ],
    payout_usd: 0.75,
    duration_min: 15,
    duration_max: 20,
    hands_required: "both",
    objects_expected: ["items", "container"],
    camera_position: "Top-down, surface level",
    example_video_url: null,
    remaining_slots: 110,
    total_completed: 190,
  },

  // ── Assembly (3) ─────────────────────────────────────────────
  {
    id: "screw_bolt",
    title: "Screw a Bolt",
    title_zh: "\u62e7\u87ba\u4e1d",
    category: "assembly",
    difficulty: "medium",
    description:
      "Record yourself screwing a bolt into a surface or object using a screwdriver. Show the full tightening motion.",
    steps: [
      "Hold the bolt in position",
      "Align the screwdriver with the bolt head",
      "Begin turning clockwise",
      "Tighten until secure",
      "Remove the screwdriver and show the result",
    ],
    payout_usd: 1.0,
    duration_min: 10,
    duration_max: 15,
    hands_required: "both",
    objects_expected: ["screwdriver", "bolt", "screw"],
    camera_position: "Close-up, showing hands and bolt",
    example_video_url: null,
    remaining_slots: 70,
    total_completed: 230,
  },
  {
    id: "plug_usb",
    title: "Plug USB Cable",
    title_zh: "\u63d2USB\u7ebf",
    category: "assembly",
    difficulty: "easy",
    description:
      "Record yourself plugging a USB cable into a port. Show the cable, port, and the insertion motion clearly.",
    steps: [
      "Hold the USB cable in one hand",
      "Identify the correct orientation",
      "Align the connector with the port",
      "Insert the cable firmly into the port",
    ],
    payout_usd: 0.5,
    duration_min: 5,
    duration_max: 10,
    hands_required: "one",
    objects_expected: ["USB cable", "port"],
    camera_position: "Close-up, device level",
    example_video_url: null,
    remaining_slots: 160,
    total_completed: 540,
  },
  {
    id: "change_bulb",
    title: "Change Light Bulb",
    title_zh: "\u6362\u706f\u6ce1",
    category: "assembly",
    difficulty: "medium",
    description:
      "Record yourself unscrewing an old light bulb and screwing in a new one. Show the twisting motion clearly.",
    steps: [
      "Ensure the lamp is unplugged or switched off",
      "Grip the old bulb and twist counter-clockwise",
      "Remove the old bulb and set it aside",
      "Pick up the new bulb",
      "Screw it in by twisting clockwise until snug",
    ],
    payout_usd: 1.0,
    duration_min: 10,
    duration_max: 15,
    hands_required: "both",
    objects_expected: ["light bulb", "lamp"],
    camera_position: "Close-up, showing bulb and socket",
    example_video_url: null,
    remaining_slots: 90,
    total_completed: 210,
  },

  // ── Personal Care (3) ────────────────────────────────────────
  {
    id: "tie_shoelaces",
    title: "Tie Shoelaces",
    title_zh: "\u7cfb\u978b\u5e26",
    category: "personal_care",
    difficulty: "easy",
    description:
      "Record yourself tying shoelaces on a shoe. Show the full tying process from loose laces to a finished knot.",
    steps: [
      "Start with the shoe and loose laces",
      "Cross the laces over each other",
      "Pull one lace under and tighten",
      "Make two loops (bunny ears)",
      "Cross the loops and pull through to knot",
    ],
    payout_usd: 0.75,
    duration_min: 10,
    duration_max: 15,
    hands_required: "both",
    objects_expected: ["shoe"],
    camera_position: "Top-down, showing shoe and hands",
    example_video_url: null,
    remaining_slots: 140,
    total_completed: 460,
  },
  {
    id: "button_shirt",
    title: "Button a Shirt",
    title_zh: "\u6263\u7ebd\u6263",
    category: "personal_care",
    difficulty: "medium",
    description:
      "Record yourself buttoning up a shirt from bottom to top. Show each button being pushed through its hole.",
    steps: [
      "Hold the shirt with buttons visible",
      "Start with the bottom button",
      "Push the button through the buttonhole",
      "Move to the next button up",
      "Continue until all buttons are fastened",
    ],
    payout_usd: 1.0,
    duration_min: 10,
    duration_max: 15,
    hands_required: "both",
    objects_expected: ["shirt"],
    camera_position: "Front-facing, torso level",
    example_video_url: null,
    remaining_slots: 100,
    total_completed: 200,
  },
  {
    id: "zip_jacket",
    title: "Zip a Jacket",
    title_zh: "\u62c9\u62c9\u94fe",
    category: "personal_care",
    difficulty: "easy",
    description:
      "Record yourself zipping up a jacket from bottom to top. Show the zipper insertion and full pull-up motion.",
    steps: [
      "Hold the jacket with the zipper open",
      "Insert the zipper pin into the slider",
      "Hold the bottom of the zipper steady",
      "Pull the slider up to the top",
    ],
    payout_usd: 0.5,
    duration_min: 5,
    duration_max: 10,
    hands_required: "both",
    objects_expected: ["jacket"],
    camera_position: "Front-facing, torso level",
    example_video_url: null,
    remaining_slots: 170,
    total_completed: 530,
  },

  // ── Office (2) ───────────────────────────────────────────────
  {
    id: "cut_paper",
    title: "Cut Paper with Scissors",
    title_zh: "\u7528\u526a\u5200\u526a\u7eb8",
    category: "office",
    difficulty: "easy",
    description:
      "Record yourself cutting a piece of paper along a line using scissors. Show the cutting motion and both hands.",
    steps: [
      "Hold the paper steady with one hand",
      "Position the scissors at the starting point",
      "Cut along the line in a smooth motion",
      "Set the scissors and paper down",
    ],
    payout_usd: 0.5,
    duration_min: 5,
    duration_max: 10,
    hands_required: "both",
    objects_expected: ["scissors", "paper"],
    camera_position: "Top-down, surface level",
    example_video_url: null,
    remaining_slots: 190,
    total_completed: 610,
  },
  {
    id: "staple_papers",
    title: "Staple Papers",
    title_zh: "\u88c5\u8ba2\u6587\u4ef6",
    category: "office",
    difficulty: "easy",
    description:
      "Record yourself stapling a small stack of papers together. Show aligning the papers and the stapling action.",
    steps: [
      "Align the stack of papers evenly",
      "Position the stapler at the corner",
      "Press down firmly to staple",
      "Check that the staple went through all pages",
    ],
    payout_usd: 0.5,
    duration_min: 5,
    duration_max: 10,
    hands_required: "both",
    objects_expected: ["stapler", "papers"],
    camera_position: "Top-down, desk level",
    example_video_url: null,
    remaining_slots: 200,
    total_completed: 700,
  },
];

/** Get all unique categories from the mock data. */
export const TASK_CATEGORIES: TaskCategory[] = [
  "kitchen",
  "cleaning",
  "organization",
  "assembly",
  "personal_care",
  "office",
];

/** Emoji icons for each category. */
export const CATEGORY_EMOJI: Record<TaskCategory, string> = {
  kitchen: "\uD83C\uDF73",
  cleaning: "\uD83E\uDDF9",
  organization: "\uD83D\uDCE6",
  assembly: "\uD83D\uDD27",
  personal_care: "\uD83E\uDEB5",
  office: "\uD83D\uDCBC",
  outdoor: "\uD83C\uDF3F",
};

/** Human-readable labels for categories. */
export const CATEGORY_LABEL: Record<TaskCategory, string> = {
  kitchen: "Kitchen",
  cleaning: "Cleaning",
  organization: "Organization",
  assembly: "Assembly",
  personal_care: "Personal Care",
  office: "Office",
  outdoor: "Outdoor",
};

/** Look up a single task by ID. */
export function getTaskById(id: string): Task | undefined {
  return MOCK_TASKS.find((t) => t.id === id);
}

/** Filter tasks by category. Returns all if category is undefined. */
export function getTasksByCategory(category?: TaskCategory): Task[] {
  if (!category) return MOCK_TASKS;
  return MOCK_TASKS.filter((t) => t.category === category);
}

/** Calculate total available earnings across all tasks. */
export function getTotalAvailableEarnings(): number {
  return MOCK_TASKS.reduce(
    (sum, t) => sum + t.payout_usd * t.remaining_slots,
    0
  );
}
